### ISSUE TITLE
slidingDownPanelLayout会报错

### ISSUE THREAD

**Issue by ouluqiang** [genius158/PullRefreshLayout#4]
倒数第二个拉下来，再拉上去报错

**Comment by genius158** [comment]
@ou3265824 好的，崩溃吗？
具体怎么操作的呢，我这里并没有复现呐

**Comment by ouluqiang** [comment]
下拉出现整屏幕的蓝底，然后再上拉就崩溃了
E/MessageQueue-JNI: java.lang.StackOverflowError
                                                                                     at com.yan.pullrefreshlayout.ViscousInterpolator.viscousFluid(ViscousInterpolator.java:31)
                                                                                     at com.yan.pullrefreshlayout.ViscousInterpolator.getInterpolation(ViscousInterpolator.java:42)
                                                                                     at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1242)
                                                                                     at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1175)
                                                                                     at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1216)
                                                                                     at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:524)
                                                                                     at android.animation.ValueAnimator.start(ValueAnimator.java:936)
                                                                                     at android.animation.ValueAnimator.start(ValueAnimator.java:946)
                                                                                     at com.yan.pullrefreshlayout.PullRefreshLayout.resetHeaderView(PullRefreshLayout.java:718)
                                                                                     at com.yan.pullrefreshlayout.PullRefreshLayout.refreshComplete(PullRefreshLayout.java:1391)
                                                                                     at com.yan.refreshloadlayouttest.widget.SlidingDownHeader.onPullChange(SlidingDownHeader.java:101)
                                                                                     at com.yan.pullrefreshlayout.PullRefreshLayout.onHeaderPullChange(PullRefreshLayout.java:912)
                                                                                     at com.yan.pullrefreshlayout.PullRefreshLayout.access$1600(PullRefreshLayout.java:32)
                                                                                     at com.yan.pullrefreshlayout.PullRefreshLayout$8.onAnimationUpdate(PullRefreshLayout.java:1084)

**Comment by genius158** [comment]
@ou3265824 确定是用的 最新的 apk吗？

**Comment by ouluqiang** [comment]
github的代码跑的

**Comment by genius158** [comment]
@ou3265824
代码是刚下的吗?以前是有这个问题，试试下面的链接
 https://github.com/genius158/PullRefreshLayout/raw/master/demo.apk
下载看看，是否有这个问题

**Comment by ouluqiang** [comment]
代码是刚下的，用连接的demo也是会崩溃，我用夜神模拟器运行的

**Comment by genius158** [comment]
@ou3265824 好吧 我去用这个模拟器试一下

**Comment by ouluqiang** [comment]
我用手机试了下demo，是没问题,模拟器的锅

**Comment by genius158** [comment]
@ou3265824  嗯，试了一下as自带的也没有问题

**Comment by genius158** [comment]
@ou3265824 刚处理了一下，夜神模拟器的奔溃，现在应该没有问题了
